<template>
    <div>
       <common-header/>
       <v-img max-height="410" src="https://myecommerce.ph/wp-content/uploads/2021/12/terms-conditions-background.png"></v-img>
       <br><br> 
       <!-- <h1 class="mx-auto text-center blue-grey--text">About Us</h1> -->
       <!-- <v-card class=""><p>Our Story</p></v-card> -->
       <v-card
      class="mx-auto"
      max-width="990"
      flat
    >
      <p class="blue-grey--text">Last updated: 2022-05-23</p>
      <strong class="blue-grey--text">Introduction </strong>
       <p class="blue-grey--text">The travel site www.dtrips.com, mobile site and Smartphone App Platforms like Android are maintained by Away Holidays LLP. By accessing or using this site or using any of its services, you are agreed on terms and conditions mentioned below, including any supplementary guidelines and future modifications. Away Holidays LLP may change, alter or remove any part of these below written Terms and Conditions without any prior notice. Any changes done in this Terms and Conditions of Use will be applicable the moment they are posted on the site. You need to re-check the “Terms & Conditions” link to be fully aware of the entire scenario.</p>
           <strong class="blue-grey--text">1. Agreement between the Clients & Away Holidays LLP </strong>
           <p class="blue-grey--text"> While accessing, using, browsing or making booking through www.dtrips.com, users have to accept that they are agreed to the terms and conditions of our portal. In case of any violation, Away Holidays LLP and its subsidiaries (including www.dtrips.com) reserve all the rights for taking any legal actions against them.</p>
           <strong class="blue-grey--text">2. Prices on the Website </strong>
           <p class="blue-grey--text">The price, which we offer on www.dtrips.com, generally includes accommodation charges, taxes (unless specified otherwise) and in special cases some meals (Breakfast /Lunch / Dinner). It never comprises any personal expense or other additional charges like telephone calls, personal-man services, entrance fees of any monuments and bar charges, etc.</p>
           <strong class="blue-grey--text"> 3. Mode of Payments & the Policies</strong>
           <p class="blue-grey--text">Our payment gateway is completely secure and customers can make the online payments through a safe transaction process that ensures their personal security codes will not be revealed in any circumstances. Modes of payment available at Away Holidays LLP for online bookings are: · Credit/Debit Cards · Net Banking · Wallet · UPI</p>
           <strong class="blue-grey--text">4. Use of the Website </strong>
           <p class="blue-grey--text">In case of your use of this website, you agree that: You have the legal authority to create an obligatory legal requirement and enter into these Terms of Use. You will use this site as per its Terms of Use. You will use the website only to make lawful bookings for you or other people for whom you are officially approved to do these kinds of bookings. You will also inform other persons about the Terms and Condition of the website You will provide accurate information about every official document and other important details like name and DOB to the site in case you are planning a trip with it. In case of any error or mistake in the process of information, you will be solely responsible for the same. All information provided by you to this site should be accurate, updated and complete, If you have an account on this site, you are advised to secure it with your login details, including login ID and password. You will be entirely responsible for any use or misuse of your account. Away Holidays LLP reserves the right to deny access to its website to anyone, at any time without any notice and for any reason, including, but not restricted to, for the violation of its Terms of Use.</p>
           <strong class="blue-grey--text">5. Communication Policy of the Site </strong>
           <p class="blue-grey--text"> On transacting with this site, you will receive an email from Away Holidays LLP for the status of your transaction. The email will be sent to the e-mail address provided by you and Away Holidays LLP is not responsible for the receipt of the supposed email in your inbox. Be careful in providing the right e-mail I’d. The customer acknowledges that the SMS sent by Away Holidays LLP is an added facility for the convenience of the customers. It is not compulsory as per the law to provide SMS service alerts to the customers. If you don’t receive any SMS for any reason, Away Holidays LLP is not liable for the same. Away Holidays LLP is not responsible to provide information about any change in flight schedules, cancellation and status of airline or hotel etc.</p>
           <strong class="blue-grey--text"> 6. Booking Policy</strong>
           <p class="blue-grey--text">The total price displayed on the site includes all applicable government taxes. In case of increase in the fare in the issuance of the Air ticket, due to airlines, miscalculation in amount due to server error and from the bank’s payment gateway issue then Away Holidays LLP reserves the right to cancel the ticket and forfeit the amount received as Cancellation Charges. The difference of amount should be paid to Away Holidays LLP after the communication from Away Holidays LLP to avoid any discomfort. You are required to pay the entire amount prior to the confirmation of your booking. To get any infant’s ticket issued, the age of infant must be below 2 yrs. and make sure that they have valid proof-of-age documents when they are checking in, and remember that the infant must be accompanied by an adult at least 18 years old. You can book no more than one infant per adult. To avail infant fares; the infant must be under 24 months of age throughout the entire itinerary that you’re booking. If the age of an infant is 24 months or above, then you need to book a separate booking as a child. To get any child ticket issued, the age of child must in between 2-12 years and make sure that they have valid proof-of-age documents when they are checking in, and remember that the child must be accompanied by an adult at least 18 years’ old All the tickets/bookings issued to the customer shall additionally be governed under the terms and conditions as laid out by the respective Airlines/Supplier. Company is not responsible for any delay or cancellation of flights from the airline's end. If a ticket is cancelled directly from the airline’s website, office or call centre, the customer needs to inform www.dtrips.com for the refund to be processed. Please note that www.dtrips.com does not get any alerts from airlines directly.</p>
           <strong class="blue-grey--text"> 7. Flight Amendment & Cancellation Policy </strong>
           <p class="blue-grey--text"> Every booking made on Away Holidays LLP is subject to cancellation charges levied by the airline, which may vary with respect to flight and booking class. www.dtrips.com levies a negligible amount of INR 180 per passenger/per sector for domestic and 220 Rs. per passenger/per sector for international air tickets as cancellation service charges. Some bookings may be non-refundable as per the specific airline’s policy. Some bookings cannot be cancelled partially as per the specific airline’s policy. Cancellations can be made online or offline through My account section or by sending an email to Away Holidays LLP (support@dtrips.com) We assist you in making various amendments for bookings. In a few cases, you need to contact the airline directly. Amendment charges on www.dtrips.com are subject to change as per the policy of the airline, which varies due to flight timings and booking class. To cancel the tickets within 24 Hrs of the journey, Away Holidays LLP recommends customers to contact the Airlines directly and after that, send the cancellation request on our website for refunds. In case of direct cancellation through airlines, refunds will be given according to airlines charges along with our service charge as above mentioned. After flight departure & in case of No Show, we don't entertain any cancellation request. In case of No-show the refund amount entirely depends upon the airlines. Away Holidays LLP has nothing to do with the refund amount. Away Holidays LLP will refund the same amount to the customer, which we receive from airlines in case of No-Show.</p>
           <strong class="blue-grey--text"> 8. Holidays Amendment & Cancellation Policy </strong>
           <p class="blue-grey--text">For cancellations done prior to the 30 days or more of the date of departure, initial deposit amount or 25% of the tour cost (if full paid) will be charged as cancellation charges. For cancellations done between 29 days to 15 days prior to the date of departure, 50% of the tour cost will be charged as cancellation charges. For cancellations done between 14 days to 8 days of the tour, 75% of the tour cost will be charged as cancellation charges For cancellations done within 8 days of the tour, 100% cancellation charges will apply and you will receive no refunds.</p>
           <strong class="blue-grey--text">9. Refund Policy </strong>
           <p class="blue-grey--text">Away Holidays LLP will process the refund only after getting cancellation request/claim from the customer/travel agent/corporate company through My account section or email. Refunds against the cancellation of air tickets will be credited directly in customer’s mode of payment after receiving the refund amount from the Airlines. Away Holidays LLP will process refund within 72 only after receiving it from the concerned Airlines/Hotel/Transporter/Other Suppliers. Due to Banking Procedures, Refund in credit cards may take duration of 72 hours while it may take 7 days in case of net banking transactions</p>
           <strong class="blue-grey--text">10. Refunds in cases where Airlines/Hotel is declared as Insolvent or Bankrupt </strong>
           <p class="blue-grey--text">Away Holidays LLP shall not be liable to pay any refunds whatsoever in cases where the Airlines/Hotel closes its operations or declares itself as insolvent The customers or clients or agents shall not hold the Away Holidays LLP liable to pay the refunds as assured at the time of booking of ticket in cases where the Airlines/Hotel closes its operation or declares itself as insolvent. On the basis of confirmation given by Airlines/Hotels/Suppliers, Away Holidays LLP may sometimes refund the amount to the customer but Away Holidays LLP reserves the right to recover the refunded amount in the event of Airlines/Hotels getting Shutted down/Non-Operational/Bankrupt.</p>
           <strong class="blue-grey--text">11. Copyright & Trademark  </strong>
           <p class="blue-grey--text"> Products, services and contents displayed on www.dtrips.com are the properties of this website. Any unauthorised copy & use of the trademark product & services without prior concern will be taken as larceny and strict actions may be taken against the concerned person/organisation/company. Away Holidays LLP gives you a limited right to enter, explore, use and transact on its site. You agree not to misuse its materials and interrupt the operation of this Site in any way. You understand that except for information, products or services supplied by Away Holidays LLP do not endorse any other information in any way. You also understand that Away Holidays LLP does not assure that files available for downloading through the site will be free from any type of viruses.</p>
           <strong class="blue-grey--text">12. Availability, Rules of Service </strong>
           <p class="blue-grey--text">Many products and services displayed on the Site may not be available for booking in your location or country. So, the reference to any such products and services on the site does not imply your particular geographical location. Products and services also are subject to availability and the company is not responsible if any product is unavailable or sold out. Each product and service offered by the website is governed by the rules and regulations of the respective service provider. You are requested to refer to their rules and regulations as well, before booking with us.</p>
           <strong class="blue-grey--text">13. Visa Guidelines  </strong>
           <p class="blue-grey--text">Please carry an applicable visa for the respective country you are visiting or transiting through. Please check-out the concerned airline and embassy for concerned Visa requirements.</p>
           <strong class="blue-grey--text">14. Transmitted Material </strong>
           <p class="blue-grey--text"> Internet communications can’t be completely private or secure. You understand that any message or information that you have sent to this site can be intercepted by others unless there is a special notice (for example, credit card information) that is encrypted. Sending a message to Away Holidays LLP does not cause the site to have any special responsibility. The copyright in the contents of this website belongs to Away Holidays LLP. Copying any part or all the contents of this website without permission of Away Holidays LLP is not allowed except to the extent that such copying or printing is essential for the purpose of availing the paid services offered.</p>
           <strong class="blue-grey--text"> 15. Offers, Contests and Interactions </strong>
           <p class="blue-grey--text">This site may run contests that may need you to send the materials or information about yourself or to offer prizes. All the offers and contests running on this website have their own rules, which you need to read before getting agreed to participate.</p>
           <strong class="blue-grey--text"> 16. Disclaimer and No Warranties </strong>
           <p class="blue-grey--text">You acknowledge that Away Holidays LLP is a conciliator, which is not accountable for any 3rd party obligations due to rates, quality, and all other instances. You particularly agree that use of the services and the site is at your solitary risk. It is your duty to assess the exactness, comprehensiveness and expediency of all advice, opinions, services, merchandise and other information provided on the site. We don’t assure that the service will be uninterrupted or error-free. Away Holidays LLP can make improvements and/or changes on its website at any point of time. Away Holidays LLP and its third-party suppliers, licensors, and partners do not guarantee or make any representations about the use or the results of the use of the services, the site or any reference sites in terms of correctness, accuracy, reliability, or otherwise. You acknowledge that uninterrupted access or use of this website can be prevented by certain factors that are not in control including, unavailability of products & services, inoperability or interruption of the Internet or other telecommunications services or certain technical work carried out on this Website. Away Holidays LLP (Away Holidays LLP) will not be answerable for any loss or damage whatsoever arising out of or in connection with any ability/inability while using the site.</p>
           <strong class="blue-grey--text">17. Hikes in Tariffs & Taxes </strong>
           <p class="blue-grey--text">We inform you on prior basis that after the finalisation of the tour package rates, for any hike in entrance fees, fuel cost, guide charges, and other services, you can be charged extra. If the government revises some taxes on travel services, clients are liable to pay that extra amount.</p>
           <strong class="blue-grey--text">18. General Terms </strong>
           <p class="blue-grey--text"> www.dtrips.com, as being a reputed and responsible travel agency, provides you the best possible information about the Hotels, Airlines, Visa and Holidays. However, it is advised to all the clients to make a personal inquiry to avoid any confusion & mess. We are not responsible for any delay & alteration in your trip due to unavoidable circumstances, which can be anything. We are not responsible for any damage, loss or injury made during enjoying the holiday packages provided by us. You are accountable for your own safety measures. We are also not accountable for any human error that went unnoticed by the clients and our staff.</p>
           <strong class="blue-grey--text">19. Unaccompanied Child </strong>
           <p class="blue-grey--text">Children below the age of 12 will not be accepted for carriage unless they are accompanied by a person of at least 18 years of age. Such child/children must be seated next to the accompanying adult. The accompanying adult is solely responsible for the well-being of the child/children traveling together with him/her. This also includes ensuring that seats are booked to ensure child/children and an accompanying adult are seated together.</p>
           <strong class="blue-grey--text">20. Airline Pregnancy Rules </strong>
           <p class="blue-grey--text">All airlines recommend the pregnant ladies to consult a doctor before travelling at any point during their pregnancy. We request all pregnant ladies to read pregnancy rules of the respective airlines before planning their trip. Some important points that need to be followed are: Take a medical clearance from your healthcare provider or doctor not more than 7 days before your journey stating that you are fit to travel. You should avoid taking flights if your pregnancy is complicated and risky in nature. You should take your due date into consideration for the return trip. If you are travelling on long-haul flights, identify if your body allows you to take a hectic flight journey as the seat-width may be uncomfortable in case of heavy pregnancy. For detailed information about the same, please contact the airline you are travelling with.</p>
           <strong class="blue-grey--text"> </strong>
           <p class="blue-grey--text"></p>
        </v-card>
        <br>
        <br>
        <br>
        <footer-page/>
        <br>
        <contact-info/>
   </div>
  </template>
  
  <script>
  import CommonHeader from '@/components/CommonHeader.vue';
  import FooterPage from '@/components/FooterPage.vue';
  import ContactInfo from '@/components/ContactInfo.vue';
  
  export default {
    components:{CommonHeader, FooterPage, ContactInfo}
  }
  </script>
  